version: "2"

services:
  build:
    image: openstreetmap.org/osmosis-build-${userId}

    links:
      - db
    volumes:
      - ${gradleUserDir}:/home/builder/.gradle
      - ${projectDir}:/project
  db:
    image: openstreetmap.org/osmosis-db
